FROM golang:1.24.2 as builder

WORKDIR /app
COPY . .
RUN go build -o app ./cmd/wervserver
WORKDIR /app/cmd/wervserver

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .
EXPOSE 8080
CMD ["./app"]