FROM golang:1.24.2

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
WORKDIR /app/cmd/wervserver
RUN go build -o app/wervserver

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/wervserver .

CMD ["./webserver"]