apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-deployment
  labels:
    app: poker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poker
  template:
    metadata:
      labels:
        app: poker
    spec:
      containers:
        - name: mon-container
          image: synerkevin/image-app:latest   # ← ton image Docker
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: poker-db-volume
            mountPath: /app/game.db.json
            subPath: game.db.json
      volumes:
        - name: poker-db-volume
          persistentVolumeClaim:
            claimName: poker-db-pvc