apiVersion: v1
kind: Service
metadata:
  name: poke-service
  labels:
    app: poker
spec:
  selector:
    app: poker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP