name: BuildAndTestGO

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run Test
        run: go test ./...
    
      - name: code quality 
        id: lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: build app
        run: |
            go build -o app ./app/cmd/webserver
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app
  
  buildDocker: 
    needs: test
    uses: ./.github/workflows/buildDocker.yaml
    with:
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

