name: Docker Build

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
  extract-image-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.image-tag.outputs.IMAGE_TAG }}
    steps:
      - id: image-tag
        run: echo "IMAGE_TAG=$(echo ${{ github.ref }} | awk -F '/' '{ print $NF }')" >> $GITHUB_OUTPUT
  build-docker-image:
    needs: [extract-image-tag]
    uses: KevPoirier/actions/.github/workflows/build-docker.yml@main
    secrets:
      docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
