name: Docker Build

on: [push, pull_request]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate short Git SHA tag
        id: generate_tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            synerkevin/image-app:latest
            synerkevin/image-app:${{ steps.generate_tag.outputs.tag }}

      - name: Update kustomization.yaml image tag
        working-directory: manifest
        run: |
          sed -i "s|newTag:.*|newTag: $TAG|" kustomization.yaml
        shell: bash
        env:
          TAG: ${{ steps.generate_tag.outputs.tag }}

      - name: Commit and push updated kustomization.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifest/kustomization.yaml
          git commit -m "Update image tag to ${{ steps.generate_tag.outputs.tag }}"
          git push